var info = {
  typeCreateHistory: [
    "Terror",
    "accion",
    "romatica",
    "comedia",
    "Aventuras",
    "Ciencia Ficción",
    "Fantasía",
  ],
  place: [
    "Colegio San Francisco",
    "IMPAWK",
    "Casa de los hermanos",
    "El chipote",
    "Casa de Aby",
    "New york",
    "Poneloya",
    "Managua",
    "Hospital",
    "Parque",
    "Un Bus",
    "Taxi",
  ],
  object: [
    "Lápiz",
    "Arbol",
    " Pluma",
    "Cuadro de Marcelino",
    "Pistola",
    "Cuchillo",
    " Pala",
    "Enchilada",
    "Cuchara",
    "Pizza",
    "Mascara",
    "Bota",
    "Mochila",
    "Alcohol",
    "Linterna",
    "Llave inglesa",
    "Telefono",
    "Mesa",
    "Silla",
    "Guitarra",
  ],
  personalFiccion: [
    "Universo de DC",
    "Universo de Marvel",
    "Universo de Harry Potter",
    "Universo de Miquimause",
    "Universo de Rick and Morty",
    "Universo de Looney Tunes",
    "Universo del Juego del Calamar",
    "Universo de Betty la fea",
    "Universo de Pasión de Gavilanes",
    "Universo de Dragon Ball",
    "Universo de Pokémon",
  ],
  participants: [
    "Osmany Ruiz",
    " Nayelis Abigail Peralta Fornos ",
    "Abigail del Carmen Carmona González",
    "Amelia Esperanza Rocha Gómez ",
    "Yuridia Valeska Flores Rugama ",
    "Betsy Carolina Ruiz Aguirre",
    "Abigail del Carmen Carmona González",
    "Anthony Jhoan Olivera Osorio ",
    "Hanssell Rocha Arcia",
    "Alondra Torrez González",
    "Sismara Victoria Canales Hernández",
    "Jeyson Osmar Pérez Acuña",
    "Jorge Luis Rodriguez Gonzalez",
    "Bayardo Noe Falcon Pinell",
    "David Josué Gaitán Rugama",
    "Enmanuel Gaitan"
  ],
};
